server:
  port: 10008
spring:
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/communications/**,/user/**,/api/**
          filters:
            - AuthenticationFilter

        - id: EMAIL-SERVICE
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/email-connector/**
          filters:
            - AuthenticationFilter

        - id: PASS-MANAGER-SERVICE
          uri: lb://PASS-MANAGER-SERVICE
          predicates:
            - Path=/password-manager/**
          filters:
            - AuthenticationFilter

        - id: URL-SHORT-SERVICE
          uri: lb://URL-SHORT-SERVICE
          predicates:
            - Path=/url-service/**
          filters:
            - AuthenticationFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        wiretap: true
  application:
    name: API-GATEWAY-SERVICE


logging:
  level:
    org.springframework.cloud.gateway: WARN
    org.springframework.http.server.reactive: WARN
    root: debug
    in.guardianservices.api_gateway: WARN


#        - id: API-GATEWAY
#          uri: lb://API-GATEWAY
#          predicates:
#            - Path=/**

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
#    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true