server:
  port: 10008

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            allowCredentials: true

      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**,/communications/**,/user/**,/api/**

        - id: EMAIL-SERVICE
          uri: lb://EMAIL-SERVICE
          predicates:
            - Path=/email-connector/**

        - id: PASS-MANAGER-SERVICE
          uri: lb://PASS-MANAGER-SERVICE
          predicates:
            - Path=/password-manager/**

        - id: API-GATEWAY
          uri: lb://API-GATEWAY
          predicates:
            - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

