server:
  port: 10007

spring:
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: http://auth-service:10001
          predicates:
            - Path=/auth/**,/communications/**,/user/**,/api/**
          filters:
            - AuthenticationFilter

        - id: EMAIL-SERVICE
          uri: http://email-connector-service:10002
          predicates:
            - Path=/email-connector/**
          filters:
            - AuthenticationFilter

        - id: PASS-MANAGER-SERVICE
          uri: http://pass-manager-service:10003
          predicates:
            - Path=/password-manager/**
          filters:
            - AuthenticationFilter

        - id: URL-SHORT-SERVICE
          uri: http://url-short-service:10004
          predicates:
            - Path=/url-service/**
          filters:
            - AuthenticationFilter

        - id: DOC-UTILITY-SERVICE
          uri: http://doc-utility-service:10005
          predicates:
            - Path=/doc-service/**
          filters:
            - AuthenticationFilter

        - id: PAYMENT-SERVICE
          uri: http://payment-service:10006
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter
      httpclient:
        wiretap: true

  application:
    name: api-gateway-service

logging:
  level:
    org.springframework.cloud.gateway: WARN
    org.springframework.http.server.reactive: WARN
    root: WARN
    in.guardianservices.api_gateway: WARN
